import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Top from "@/components/Top";
import Phone from "@/components/Phone";
import { LoginFunction } from "@/hooks/LoginFunction";
import Name from "@/hooks/Name";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "گالری ایلیا",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo/logo.webp",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Phone></Phone>
        <Name>
          <LoginFunction>
            <Header></Header>
            {children}
            <Top></Top>
            <Footer></Footer>
          </LoginFunction>
        </Name>
      </body>
    </html >
  );
}
